You are recommended to run this within [Visual Studio Code](https://code.visualstudio.com/Download)!


# Getting Started
Place your combos in 'accounts.txt'. You can use [Sodium](https://discord.gg/combo) to get combos.
Place proxies inside of 'proxies.txt'. You can get proxies from [ProxyScrape](https://proxyscrape.com).

Edit 'config.json' and replace 'capbypass_key' with your captcha key. 
You can change the amount of threads. The more threads you use the faster the bruter will work but it will take up more resources.
Change 'webhook_url' to your discord webhook url for notifications when you get hits.

If you don't already have python installed you should probably do that now lol https://python.org/

**Make sure you have the required modules installed!**

``pip install -r requirements.txt``

Now you can run the bruter using VSC (Recommended) or with the terminal using ``python main.py``.

To get a captcha key check out https://capbypass.com!

## https://discord.gg/PGer
